In [1]:
from qutip import *
from sympy import Matrix, latex

ket0 = basis(2,0) # Up State
ket1 = basis(2,1) # Down State


# Wavefunction given for in the 3_1
psi = (tensor(ket1, ket0, ket0) + tensor(ket0, ket1, ket0) + tensor(ket1, ket1, ket0) + tensor(ket0, ket1, ket1)).unit()
rho = ket2dm(psi)

In [2]:
rho_sympy = Matrix(rho.full())
print(latex(rho_sympy))

\left[\begin{matrix}0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0.25 & 0.25 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0.25 & 0.25 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0.25 & 0.25 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0.25 & 0.25 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\end{matrix}\right]


In [3]:
rho_partial = partial_transpose(rho, [1,0,0]) # Partial Transpose with respect to subsystem a
eigenvals = rho_partial.eigenenergies()

for i in range(len(eigenvals)):
    print("%.5f"%eigenvals[i],end=", ")

print("\n")
rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))

-0.43301, -0.00000, 0.00000, 0.00000, 0.00000, 0.25000, 0.43301, 0.75000, 

\left[\begin{matrix}0 & 0 & 0 & 0 & 0 & 0 & 0.25 & 0.25\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0.25 & 0.25 & 0 & 0 & 0.25 & 0.25\\0 & 0 & 0.25 & 0.25 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.25 & 0 & 0.25 & 0 & 0.25 & 0 & 0.25 & 0\\0.25 & 0 & 0.25 & 0 & 0 & 0 & 0 & 0\end{matrix}\right]


In [4]:
rho_partial = partial_transpose(rho, [0,1,0]) # Partial Transpose with respect to subsytem b
eigenvals = rho_partial.eigenenergies()
print(eigenvals)

rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))


[-3.53553391e-01 -1.44395746e-16  0.00000000e+00  0.00000000e+00
  2.39382901e-17  1.46446609e-01  3.53553391e-01  8.53553391e-01]
\left[\begin{matrix}0 & 0 & 0 & 0 & 0 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0.25 & 0\\0 & 0 & 0.25 & 0.25 & 0 & 0 & 0.25 & 0\\0 & 0 & 0.25 & 0.25 & 0 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.25 & 0.25 & 0.25 & 0.25 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\end{matrix}\right]


In [5]:
rho_partial = partial_transpose(rho_partial, [0,0,1]) # Partial Transpose with respect to subsystem c
eigenvals = rho_partial.eigenenergies()
print(eigenvals)

rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))


[-4.33012702e-01 -4.67016704e-18  4.49117058e-17  5.16626570e-17
  1.59443983e-16  2.50000000e-01  4.33012702e-01  7.50000000e-01]
\left[\begin{matrix}0 & 0 & 0 & 0 & 0 & 0 & 0.25 & 0.25\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0.25 & 0.25 & 0 & 0 & 0.25 & 0.25\\0 & 0 & 0.25 & 0.25 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.25 & 0 & 0.25 & 0 & 0.25 & 0 & 0.25 & 0\\0.25 & 0 & 0.25 & 0 & 0 & 0 & 0 & 0\end{matrix}\right]


In [6]:
# partial trace with respect to a
rho_pa = ptrace(rho,[1,2])
rho_pa_sympy = Matrix(rho_pa)
print(latex(rho_pa_sympy))

\left[\begin{matrix}0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0\\0.25 & 0 & 0.5 & 0.25\\0 & 0 & 0.25 & 0.25\end{matrix}\right]


In [7]:
# partial trace with respect to b
rho_pb = ptrace(rho,[0,2])
rho_pb_sympy = Matrix(rho_pb)
print(latex(rho_pb_sympy))


\left[\begin{matrix}0.25 & 0.25 & 0.25 & 0\\0.25 & 0.25 & 0.25 & 0\\0.25 & 0.25 & 0.5 & 0\\0 & 0 & 0 & 0\end{matrix}\right]


In [8]:
# partial trace with respect to c
rho_pc = ptrace(rho,[0,1])
rho_pc_sympy = Matrix(rho_pc)
print(latex(rho_pc_sympy))

\left[\begin{matrix}0 & 0 & 0 & 0\\0 & 0.5 & 0.25 & 0.25\\0 & 0.25 & 0.25 & 0.25\\0 & 0.25 & 0.25 & 0.25\end{matrix}\right]


In [9]:
rho_a_pb = partial_transpose(rho_pa, [1,0]) # partial trace of p_bc with respect to a
eigenvals = rho_a_pb.eigenenergies()

print(eigenvals)

matrix = Matrix(rho_a_pb.full())
print(latex(matrix))

[0.00000000e+00 9.81263409e-18 2.50000000e-01 7.50000000e-01]
\left[\begin{matrix}0.25 & 0 & 0.25 & 0\\0 & 0 & 0 & 0\\0.25 & 0 & 0.5 & 0.25\\0 & 0 & 0.25 & 0.25\end{matrix}\right]


In [10]:
rho_a_pc = partial_transpose(rho_pc, [1,0]) # partial trace of p_bc with respect to a
eigenvals = rho_a_pc.eigenenergies()

print(eigenvals)

matrix = Matrix(rho_a_pc.full())
print(latex(matrix))

[-0.23296291  0.12059048  0.37940952  0.73296291]
\left[\begin{matrix}0 & 0 & 0 & 0.25\\0 & 0.5 & 0 & 0.25\\0 & 0 & 0.25 & 0.25\\0.25 & 0.25 & 0.25 & 0.25\end{matrix}\right]


In [11]:
rho_b_pa = partial_transpose(rho_pb, [1,0]) # partial trace of p_bc with respect to a
eigenvals = rho_b_pa.eigenenergies()

print(eigenvals)

matrix = Matrix(rho_b_pa.full())
print(latex(matrix))

[-0.23296291  0.12059048  0.37940952  0.73296291]
\left[\begin{matrix}0.25 & 0.25 & 0.25 & 0.25\\0.25 & 0.25 & 0 & 0\\0.25 & 0 & 0.5 & 0\\0.25 & 0 & 0 & 0\end{matrix}\right]


### Four Qubit System 

In [18]:
import numpy as np
psi_1 = 1/np.sqrt(2) * (tensor(ket0, ket0, ket0, ket0) + tensor(ket1, ket1, ket1, ket0))
psi_2 = 1/np.sqrt(2) * (tensor(ket0, ket0, ket0, ket0) + tensor(ket1, ket1, ket0, ket1))
psi_3 = 1/np.sqrt(2) * (tensor(ket0,ket1,ket0,ket0) + tensor(ket1,ket1,ket1,ket0))

psi = (psi_1 + psi_2 + psi_3).unit()
rho = ket2dm(psi)

In [20]:
rho_sympy = Matrix(rho.full())
print(latex(rho_sympy))

\left[\begin{array}{cccccccccccccccc}0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2 & 0.4 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.1 & 0.2 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.1 & 0.2 & 0\\0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0

In [23]:
# partial transpose with respect to subsystem A
rho_partial = partial_transpose(rho, [1,0,0,0]) # Partial Transpose with respect to subsystem a
eigenvals = rho_partial.eigenenergies()

for i in range(len(eigenvals)):
    print("%.3f"%eigenvals[i],end=", ")

print("\n")
rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))

-0.500, -0.000, -0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.500, 0.500, 0.500, 

\left[\begin{array}{cccccccccccccccc}0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0.2 & 0.4 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0.1 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 &

In [25]:
# partial transpose with respect to subsystem B
rho_partial = partial_transpose(rho, [0,1,0,0]) # Partial Transpose with respect to subsystem a
eigenvals = rho_partial.eigenenergies()

for i in range(len(eigenvals)):
    print("%.3f"%eigenvals[i],end=", ")

print("\n")
rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))

-0.447, -0.000, -0.000, -0.000, -0.000, -0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.276, 0.447, 0.724, 

\left[\begin{array}{cccccccccccccccc}0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0.2 & 0.4 & 0 & 0 & 0.1 & 0.2 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0.4 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 

In [26]:
# partial transpose with respect to subsystem C
rho_partial = partial_transpose(rho, [0,0,1,0]) # Partial Transpose with respect to subsystem a
eigenvals = rho_partial.eigenenergies()

for i in range(len(eigenvals)):
    print("%.3f"%eigenvals[i],end=", ")

print("\n")
rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))

-0.490, -0.000, -0.000, -0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.400, 0.490, 0.600, 

\left[\begin{array}{cccccccccccccccc}0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.4 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.1 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2\\0.2 

In [27]:
# partial transpose with respect to subsystem D
rho_partial = partial_transpose(rho, [0,0,0,1]) # Partial Transpose with respect to subsystem a
eigenvals = rho_partial.eigenenergies()

for i in range(len(eigenvals)):
    print("%.3f"%eigenvals[i],end=", ")

print("\n")
rho_partial_sympy = Matrix(rho_partial.full())
print(latex(rho_partial_sympy))

-0.300, -0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.100, 0.300, 0.900, 

\left[\begin{array}{cccccccccccccccc}0.4 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.4 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\0 & 0.2 & 0 & 0 & 0 & 0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.2\\0 & 0 